module.exports = {
  USER_CREATE_SUCCESS: "CREATE SUCCESS",
  USER_EXIST: "USER EXIST",
  USER_DELETE_SUCCESS: "DELETE SUCCESS",
  USER_NOT_EXIST: "USER NOT EXIST",
  USER_UPDATE_SUCCESS: "USER UPDATE SUCCESS",
  USER_NORMAL_SUCCESS: "SUCCESS",
  USER_NORMAL_FAILED: "FAILED",
  USER_PASSWORD_NOT_CORRECT: "USER PASSWORD NOT CORRECT",
  USER_LOGIN_SUCCESS: "USER LOGIN SUCCESS",
  USER_NOT_VALID_QUERY: "NOT VALID QUERY"
};
